x, y, z = 3, 5, 7
print("x =",x,", y =",y,", z =",z)
print("x == 3      ->",x == 3)
print("x < y       ->",x < y)
print("x >= y      ->",x >= y)
print("x <= y      ->",x <= y)
print("x != y - 2  ->",x != y - 2)
print("x < 10      ->",x < 10)
print("x >= 0  and x < 10",x >= 0 and x < 10)
print("x < 0   and x < 10",x < 0 and x < 10)
print("x >= 0  and x < 2",x >= 0 and x < 2)
print("x < 0   or  x < 10",x < 0 or x < 10)
print("x > 0   or  x < 10",x > 0 or x < 10)
print("x < 0   or  x > 10",x < 0 or x > 10)

